version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: cmsuser       # Database username
      POSTGRES_PASSWORD: cmspassword  # Database password
      POSTGRES_DB: cmsdb           # Database name
    ports:
      - "5432:5432"                # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"                # Expose Redis port
    volumes:
      - redis_data:/data           # Persist Redis data

volumes:
  postgres_data:   # Named volume for PostgreSQL
  redis_data:      # Named volume for Redis
